spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true